### ISSUE TITLE
sys_hru_folder not set correctly

### ISSUE THREAD

**Issue by jdduh** [PSU-CSAR/vb-bagis-p#22]
I suspect that the sys_hru_folder value is not set correctly (see attached picture). The folder should be a path, not just the name of the HRU). There is a separate variable (sys_hru_name) for passing the HRU name to the model.

![bagis-p_sys_hru_folder](https://cloud.githubusercontent.com/assets/11510708/10855569/9bb65ec6-7eff-11e5-8477-75add977b4f6.JPG)

**Comment by lbross** [comment]
I think this is a problem with the parameter type used in the model rather than with BAGIS-P. I verified that BAGIS-P is trying to pass the full path. When I ran the model manually, it truncated the value of the sys_hru_folder to be just the folder name. Note that sys_aoi_path is defined as a string parameter and sys_hru_folder should probably be defined the same way.

After updating the parameter type, the model ran successfully but did not return any results. Is it supposed to? Or is it a work in progress?

**Comment by jdduh** [comment]
The soil_moist_recharge_parameters model is 99% finished. What's left is to add a message when soil_rechr_max value is larger than the soil_moist_max value (and thus replaced by the soil_moist_max value). After running the model, you should see the output parameter table containing four parameter columns and their values were set. The model sends a warning message at the end notifying users that soil_moist_init and soil_rechr_init are set as 25% of the max values. We need to modify BAGIS-P so that the warning messages are captured in the log file. See #19.

**Comment by lbross** [comment]
I am working on issue #19 and am close. Also working on the log file. The soil_moist_recharge_parameters model does not return any values for me in teton_aoi. Everything is set to -99. No error messages are generated, nor is any data. Let me know if you'd like more information on this. Closing this ticket as there are no changes to be made for sys_hru_folder on the BAGIS-P side.

**Comment by jdduh** [comment]
Confirm that the sys_hru_folder was set correctly by BAGIS-P. The folder variable type does contain the complete path information. Is there a place I can download the teton_aoi?

**Comment by lbross** [comment]
The sys_hru_folder is set correctly by BAGIS-P. The display in the screenshot you provided is deceiving. Even when you supply the whole path through ArcToolbox, it still only displays the folder. Will address the issue of the new model on another open issue.
