### ISSUE TITLE
Global Data Manager - Clip Selected layer(s) to AOI tool buffer size

### ISSUE THREAD

**Issue by jdduh** [PSU-CSAR/vb-bagis-p#35]
Dave reports that the data manager clips the soil layers to the AOIs with a buffer that is too small. As a result, many edge HRUs have very small numbers of soil cells that contain data and have skewed parameter estimates. Is there a way to set the clipping buffers based on the input layers' cell size? BAGIS uses 1000-meter buffer to clip the PRISM layers, which have a cell size of around 1000 meters (935 meters). The STATSGO soil layers also have a cell size of around 1000 meters.

**Comment by lbross** [comment]
This form uses the BA_ClipLayerToAoi function which is shared across BAGIS. Rather than set a buffer, this function selects an aoi vector layer to clip to. The clip file will be either the buffered aoi vector or the prism aoi vector. The prism aoi vector is selected if clipCellSize > (aoiCellSize \* 10). I ran a test and the prism buffer is used when I clip some sample soils data in the data manager. I laid the prism aoi vector on top of the clipped file to confirm this.  Is the prism aoi layer not large enough for soils data?

**Comment by jdduh** [comment]
It turns out the PRISM that David clipped was a legacy file. The tool works correctly. Sorry to bring this up!

**Comment by lbross** [comment]
This is good news! I'll take it.
